#!/usr/bin/env sh

FILE=$(mktemp -t maybe-run.XXXXXXXXXXXXXXXXX) || { echo "Failed creating file"; return; }
cat > "$FILE"

while :
do
    echo 'Command:' "$@"
    echo 'What do you want to do with the input?'
    echo "(s)how    (e)dit    (r)un     (q)uit"
    read ANSWER </dev/tty

    case "$ANSWER" in
        [Ss]* ) echo ; less -FX "$FILE" ; echo ; ;;
        [Ee]* ) ${VISUAL:-${EDITOR:-nano}} "$FILE" < /dev/tty ;;
        [Rr]* ) cat "$FILE" | "$@" ; break;;
        [Qq]* ) break;;
    esac
done

rm "$FILE"
